FROM python:3

WORKDIR /app

ADD . /app

COPY ./requirements.txt /app/

RUN pip install -r /app/requirements.txt

COPY . /app

# RUN pip install -r requirements.txtcd


CMD ["python","app.py"]

EXPOSE 80
